#!/usr/bin/env node
/**
 * Regenerate the data-derived figures in README.md and README.zh.md.
 *
 * Every number in those files used to be typed by hand while `data/*.jsonl` was
 * regenerated by a scheduled workflow, so the two could only diverge. Measured
 * on 2026-08-18: the READMEs claimed 6929 enumerated, 1698 probed and 1167
 * catalogued while the data held 7111, 2398 and 1660. The repository's own claim
 * is that its figures are reproducible, so a stale figure is not a cosmetic
 * problem.
 *
 * Prose stays hand-written. Only regions between the markers below are replaced:
 *
 *   <!-- census:begin NAME -->
 *   ...generated...
 *   <!-- census:end NAME -->
 *
 * A marker naming an unknown region, or a region with no marker, is an error
 * rather than a silent no-op: a typo would otherwise leave a figure frozen while
 * the rest updated, which is the failure this script exists to remove.
 *
 *   node scripts/render-readme.mjs            # rewrite in place
 *   node scripts/render-readme.mjs --check    # exit 1 if anything is stale
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const ROOT = new URL('..', import.meta.url).pathname

/** Read a JSONL file into records, or null when it does not exist yet. */
function load(name) {
  if (!existsSync(`${ROOT}data/${name}.jsonl`)) return null
  return readFileSync(`${ROOT}data/${name}.jsonl`, 'utf8')
    .split('\n')
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line))
}

/** Count occurrences of a field value. */
function tally(rows, key) {
  const counts = new Map()
  for (const row of rows) counts.set(row[key], (counts.get(row[key]) ?? 0) + 1)
  return counts
}

/** Format a share of a total to one decimal place. */
function share(count, total) {
  return total === 0 ? '0%' : `${((count / total) * 100).toFixed(1)}%`
}

const raw = load('repos-raw')
const contract = load('contract-v3')
const surface = load('surface-v3')
const install = load('installability-v3')
const decay = load('decay')
const catalog = load('catalog')
const npmManifest = load('npm-manifest') ?? []
const ratings = load('ratings') ?? []

const verdicts = tally(contract, 'verdict')

/** Star band membership, in the order published. */
const BANDS = [
  ['0', (stars) => stars === 0],
  ['1-2', (stars) => stars >= 1 && stars <= 2],
  ['3-9', (stars) => stars >= 3 && stars <= 9],
  ['10-49', (stars) => stars >= 10 && stars <= 49],
  ['50+', (stars) => stars >= 50],
]

const starsByRepo = new Map(raw.map((row) => [row.full_name, row.stars ?? 0]))

/**
 * Markdown table header plus separator for the given language.
 * @param en - English column names.
 * @param zh - Chinese column names.
 * @param lang - 'en' or 'zh'.
 * @returns the header and separator lines.
 */
function headerFor(en, zh, lang) {
  const cols = lang === 'zh' ? zh : en
  const n = cols.split('|').filter((cell) => cell.trim()).length
  return `${cols}\n| ${Array(n).fill('---').join(' | ')} |`
}

/** Compliance share per star band, plus the overall row. */
function complianceRows(labels) {
  const rows = [labels.header, '| --- | --- |']
  let okAll = 0
  let nAll = 0
  for (const [label, inBand] of BANDS) {
    let ok = 0
    let n = 0
    for (const row of contract) {
      const stars = starsByRepo.get(row.repo)
      if (stars === undefined || !inBand(stars)) continue
      n += 1
      if (row.verdict === 'CONTRACT_OK') ok += 1
    }
    okAll += ok
    nAll += n
    const value = share(ok, n)
    rows.push(`| ${label} | ${label === '50+' ? `**${value}**` : value} |`)
  }
  rows.push(`| ${labels.all} | ${share(okAll, nAll)} |`)
  return rows.join('\n')
}

/** Verdict table, ordered by count then name so ties are stable. */
function verdictRows(lang) {
  const rows = [...verdicts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([verdict, count]) => `| \`${verdict}\` | ${count} | ${share(count, contract.length)} |`)
    .join('\n')
  return `${headerFor('| Verdict | Count | Share |', '| 判定 | 数量 | 占比 |', lang)}\n${rows}`
}

/** Surface-attribution table with a fixed row order and localised bases. */
function surfaceRows(basis, lang) {
  const counts = tally(surface, 'confidence')
  const rows = ['high', 'declared', 'medium', 'low', 'none']
    .map((level) => {
      const count = counts.get(level) ?? 0
      return `| \`${level}\` | ${basis[level]} | ${count} | ${share(count, surface.length)} |`
    })
    .join('\n')
  return `${headerFor('| Confidence | Basis | Count | Share |', '| 置信度 | 依据 | 数量 | 占比 |', lang)}\n${rows}`
}

/** Installability table. */
function installRows(meanings, lang) {
  const counts = tally(install, 'installable')
  const ordered = ['published', 'git-only', 'unpublishable-scope', 'unknown', 'unnamed']
  // Every state present in the data must appear. A hardcoded three-state list
  // would have silently dropped `unknown` and `unnamed` rows — the same defect
  // that removed 416 `declared` entries from PLUGINS.md when that tier was added.
  const missing = [...counts.keys()].filter((state) => !ordered.includes(state))
  if (missing.length > 0) {
    throw new Error(
      `installability state(s) ${missing.join(', ')} have no row; add them to installRows`,
    )
  }
  const rows = ordered
    .filter((state) => (counts.get(state) ?? 0) > 0 || state !== 'unnamed')
    .map((state) => `| \`${state}\` | ${meanings[state]} | ${counts.get(state) ?? 0} |`)
    .join('\n')
  return `${headerFor('| Verdict | Meaning | Count |', '| 判定 | 含义 | 数量 |', lang)}\n${rows}`
}

/** Decay table, with the never-observed states pinned at zero. */
function decayRows(lang) {
  const counts = tally(decay, 'state')
  const rows = ['live', 'archived', 'gone', 'unbundled', 'dormant', 'inconclusive']
    .map((state) => `| \`${state}\` | ${counts.get(state) ?? 0} |`)
    .join('\n')
  return `${headerFor('| State | Count |', '| 状态 | 数量 |', lang)}\n${rows}`
}

/**
 * Entries flagged as actually decayed, with the list capped.
 *
 * `inconclusive` is deliberately excluded: it means the probe could not reach a
 * conclusion, not that the entry decayed, and listing it as a flag would report
 * a quota shortfall as a property of someone's repository. Its count is published
 * separately through the `n-inconclusive` region.
 *
 * The list is capped because it is prose, not data — `data/decay.jsonl` is the
 * complete record. An uncapped table reached 450 lines once the catalogue grew.
 *
 * @param labels - localised header, column names, empty message and overflow note.
 * @returns markdown.
 */
function decayFlagged(labels) {
  const DECAYED = ['gone', 'archived', 'dormant', 'unbundled']
  const flagged = decay
    .filter((row) => DECAYED.includes(row.state))
    .sort((a, b) => a.state.localeCompare(b.state) || a.repo.localeCompare(b.repo))
  if (flagged.length === 0) return labels.empty
  const shown = flagged.slice(0, 12)
  const lines = [
    labels.header(flagged.length),
    '',
    `| ${labels.entry} | ${labels.state} |`,
    '| --- | --- |',
    ...shown.map((row) => `| \`${row.repo}\` | ${row.state}${row.detail ? ` — ${row.detail}` : ''} |`),
  ]
  if (flagged.length > shown.length) {
    lines.push('', labels.more(flagged.length - shown.length))
  }
  return lines.join('\n')
}

/** Meanings for the published-manifest states, kept beside the region. */
const NPM_MEANINGS = {
  'bundle-ok': 'the published manifest declares `dsh.bundle`',
  'bundle-missing': '**the published manifest declares no `dsh.bundle`** — DSH refuses it as a profile bundle',
  'package-missing': 'the declared name no longer resolves on the registry',
  unreadable: 'the registry could not be read; not a statement about the package',
}

/** Chinese meanings for the same states. */
const NPM_MEANINGS_ZH = {
  'bundle-ok': '已发布的清单声明了 `dsh.bundle`',
  'bundle-missing': '**已发布的清单没有 `dsh.bundle`**——DSH 会拒绝把它作为 profile bundle 加载',
  'package-missing': '声明的包名已无法在 registry 上解析',
  unreadable: 'registry 读取失败；这不是对该包的判断',
}

/** Regions for both files. Keys must match the markers in the documents. */
const REGIONS = {
  'compliance-en': () => complianceRows({
    header: '| Stars | Satisfies the plugin contract |',
    all: 'all',
  }),
  'compliance-zh': () => complianceRows({
    header: '| Star | 符合插件契约的比例 |',
    all: '全部',
  }),
  'verdicts': (lang) => verdictRows(lang),
  'surface-en': () => surfaceRows({
    high: 'depends on `@deepseek-ai/dsh-client-*` (client) or `@deepseek-ai/dsh-host-*` and host-only packages (host)',
    declared: "the plugin's own `dsh.client` or `dsh.host` block declares the surface",
    medium: 'depends on `@deepseek-ai/*`, but no dependency distinguishes client from host — surface `indeterminate`',
    low: 'no `@deepseek-ai/*` dependency; surface guessed from a name or description keyword',
    none: 'no dependency evidence and no keyword match — **not attributed at all**',
  }, 'en'),
  'surface-zh': () => surfaceRows({
    high: '依赖 `@deepseek-ai/dsh-client-*`（client 侧）或 `@deepseek-ai/dsh-host-*` 及 host 专用包（host 侧）',
    declared: '插件自己的 `dsh.client` 或 `dsh.host` 块声明了该 surface',
    medium: '有 `@deepseek-ai/*` 依赖，但没有一个依赖能区分 client 与 host，surface 记为 `indeterminate`',
    low: '没有 `@deepseek-ai/*` 依赖，surface 由名称或描述中的关键词猜测',
    none: '既无依赖证据也无关键词命中——**根本没有归因**',
  }, 'zh'),
  'install-en': () => installRows({
    published: 'the declared name resolves on the npm registry',
    'git-only': 'absent from npm; installable from a Git specifier',
    'unpublishable-scope': 'names itself under `@deepseek-ai/` from a repository outside that organisation',
    unknown: '**the registry did not answer** — not a statement about the package',
    unnamed: 'the manifest declares no package name',
  }, 'en'),
  'install-zh': () => installRows({
    published: '声明的包名可在 npm registry 解析',
    'git-only': '不在 npm 上；只能用 Git specifier 安装',
    'unpublishable-scope': '仓库不属于该组织，却用 `@deepseek-ai/` 命名自己',
    unknown: '**registry 没有给出结论**——这不是对该包的判断',
    unnamed: '清单没有声明包名',
  }, 'zh'),
  'decay': (lang) => decayRows(lang),
  'decay-flagged-en': () => decayFlagged({
    header: (n) => `The ${n} entries flagged as decayed (\`inconclusive\` is not decay and is excluded):`,
    entry: 'Entry',
    state: 'State',
    empty: 'No entry is currently flagged as decayed.',
    more: (n) => `...and ${n} more in \`data/decay.jsonl\`.`,
  }),
  'decay-flagged-zh': () => decayFlagged({
    header: (n) => `被判定为失效的 ${n} 个条目（\`inconclusive\` 不是失效，已排除）：`,
    entry: '条目',
    state: '状态',
    empty: '当前没有条目被判定为失效。',
    more: (n) => `……另有 ${n} 个见 \`data/decay.jsonl\`。`,
  }),
  // Inline figures, kept as single-value regions so prose can wrap around them.
  'n-enumerated': () => String(raw.length),
  'n-probed': () => String(contract.length),
  'n-declared': () => String(contract.filter((row) => (row.tier ?? 0) >= 1).length),
  'n-tier23-fail': () => String(
    contract.filter((row) => ['PATCH_FILE_MISSING', 'PATCH_FILE_EMPTY_OR_INVALID'].includes(row.verdict)).length,
  ),
  'n-vendored': () => String(verdicts.get('VENDORED_HARNESS') ?? 0),
  'n-catalog-rows': () => String(catalog.length),
  'max-age-days': () => {
    const ages = decay.map((row) => row.ageDays).filter((value) => typeof value === 'number')
    return ages.length === 0 ? 'unknown' : String(Math.max(...ages))
  },
  'n-dep-evidence': () => {
    const counts = tally(surface, 'confidence')
    return String((counts.get('high') ?? 0) + (counts.get('medium') ?? 0))
  },
  'n-declared': () => String(tally(surface, 'confidence').get('declared') ?? 0),
  'npm-manifest': () => {
    const counts = tally(npmManifest, 'state')
    const total = npmManifest.length
    const rows = ['bundle-ok', 'bundle-missing', 'package-missing', 'unreadable']
      .map((state) => {
        const count = counts.get(state) ?? 0
        return `| \`${state}\` | ${NPM_MEANINGS[state]} | ${count} | ${share(count, total)} |`
      })
      .join('\n')
    return `${headerFor('| State | Meaning | Count | Share |', '| 状态 | 含义 | 数量 | 占比 |', 'en')}\n${rows}`
  },
  'npm-manifest-zh': () => {
    const counts = tally(npmManifest, 'state')
    const total = npmManifest.length
    const rows = ['bundle-ok', 'bundle-missing', 'package-missing', 'unreadable']
      .map((state) => {
        const count = counts.get(state) ?? 0
        return `| \`${state}\` | ${NPM_MEANINGS_ZH[state]} | ${count} | ${share(count, total)} |`
      })
      .join('\n')
    return `${headerFor('| State | Meaning | Count | Share |', '| 状态 | 含义 | 数量 | 占比 |', 'zh')}\n${rows}`
  },
  'n-npm-checked': () => String(npmManifest.length),
  'n-npm-broken': () => {
    const counts = tally(npmManifest, 'state')
    return String((counts.get('bundle-missing') ?? 0) + (counts.get('package-missing') ?? 0))
  },
  'pct-npm-broken': () => {
    const counts = tally(npmManifest, 'state')
    const bad = (counts.get('bundle-missing') ?? 0) + (counts.get('package-missing') ?? 0)
    return share(bad, npmManifest.length)
  },
  'n-rated': () => String(ratings.length),
  'n-onematch': () => String(ratings.filter((row) => (row.matches ?? 0) === 1).length),
  'rating-matches-max': () => String(ratings.reduce((max, r) => Math.max(max, r.matches ?? 0), 0)),
  'rating-matches-mean': () => (ratings.length === 0
    ? '0'
    : (ratings.reduce((sum, r) => sum + (r.matches ?? 0), 0) / ratings.length).toFixed(1)),
  'rating-spread': () => {
    if (ratings.length === 0) return 'no ratings yet'
    const values = ratings.map((r) => r.rating ?? 0)
    return `${Math.round(Math.min(...values))} to ${Math.round(Math.max(...values))}`
  },
  // Bands by rating value, plus the value distribution underneath.
  //
  // The bands used to cut the sorted entries into four equally sized groups,
  // which reported a uniform shape the data does not have: with 96% of entries at
  // one match the ratings sit on a few discrete values, so a quantity-based cut
  // split the 586 entries sharing one rating across two bands and printed two
  // rows whose rating ranges both contained that value. Boundaries now fall on
  // value edges — the quartile position picks which value ends a band, and no
  // value is ever split — so the bands do not overlap and each states the rating
  // range it actually covers. Band sizes are then uneven, and that unevenness is
  // the finding: the population piles up at each end.
  //
  // The distribution table below names each value, because a band that holds one
  // dominant value hides how concentrated the ratings are. Values holding fewer
  // than MIN_DISTRIBUTION_GROUP entries collapse into one row: they are
  // individual entries, and listing them would bury the shape both tables exist
  // to show.
  'rating-bands': (lang) => {
    if (ratings.length === 0) return '_No comparisons have been played yet._'
    const groups = new Map()
    for (const row of ratings) {
      const value = Math.round(row.rating ?? 0)
      const group = groups.get(value) ?? { entries: 0, matches: 0 }
      group.entries += 1
      group.matches += row.matches ?? 0
      groups.set(value, group)
    }
    const values = [...groups.keys()].sort((a, b) => b - a)
    const bandCount = 4
    // Each quartile position picks the value that ends a band, so boundaries sit
    // between values rather than inside one.
    const bounds = []
    let cumulative = 0
    let nextTarget = 0
    for (const value of values) {
      cumulative += groups.get(value).entries
      while (nextTarget < bandCount - 1 && cumulative >= (ratings.length * (nextTarget + 1)) / bandCount) {
        bounds.push(value)
        nextTarget += 1
      }
    }
    const labels = lang === 'zh'
      ? ['最高档', '次高档', '次低档', '最低档']
      : ['top band', 'second band', 'third band', 'bottom band']
    const rows = []
    for (let i = 0; i < labels.length; i += 1) {
      const upper = i === 0 ? null : bounds[i - 1]
      const lower = i < bounds.length ? bounds[i] : null
      const band = values.filter((value) => {
        if (upper !== null && value >= upper) return false
        if (lower !== null && value < lower) return false
        return true
      })
      if (band.length === 0) continue
      const entries = band.reduce((sum, value) => sum + groups.get(value).entries, 0)
      const matches = band.reduce((sum, value) => sum + groups.get(value).matches, 0)
      const range = band[0] === band[band.length - 1]
        ? String(band[0])
        : `${band[band.length - 1]}\u2013${band[0]}`
      rows.push(`| ${labels[i]} | ${range} | ${entries} | ${(matches / entries).toFixed(1)} |`)
    }
    return `${headerFor('| Band | Rating range | Entries | Mean matches |', '| 分档 | 评级区间 | 条目数 | 平均场次 |', lang)}\n${rows.join('\n')}`
  },
  // The distribution by rating value: which values exist, how many entries sit on
  // each, and how much evidence those entries carry.
  'rating-distribution': (lang) => {
    if (ratings.length === 0) return '_No comparisons have been played yet._'
    const MIN_DISTRIBUTION_GROUP = 10
    const groups = new Map()
    for (const row of ratings) {
      const value = Math.round(row.rating ?? 0)
      const group = groups.get(value) ?? { entries: 0, matches: 0 }
      group.entries += 1
      group.matches += row.matches ?? 0
      groups.set(value, group)
    }
    const values = [...groups.keys()].sort((a, b) => b - a)
    const line = (label, group) =>
      `| ${label} | ${group.entries} | ${(group.matches / group.entries).toFixed(1)} |`
    const rest = values.filter((value) => groups.get(value).entries < MIN_DISTRIBUTION_GROUP)
    const rows = values
      .filter((value) => groups.get(value).entries >= MIN_DISTRIBUTION_GROUP)
      .map((value) => line(value, groups.get(value)))
    if (rest.length > 0) {
      const tail = rest.reduce(
        (sum, value) => ({
          entries: sum.entries + groups.get(value).entries,
          matches: sum.matches + groups.get(value).matches,
        }),
        { entries: 0, matches: 0 },
      )
      rows.push(line(
        lang === 'zh' ? `其他 ${rest.length} 个分数值` : `other ${rest.length} values`,
        tail,
      ))
    }
    return `${headerFor('| Rating | Entries | Mean matches |', '| 评级 | 条目数 | 平均场次 |', lang)}\n${rows.join('\n')}`
  },
  'n-inconclusive': () => String(decay.filter((row) => row.state === 'inconclusive').length),
  'pct-inconclusive': () => share(decay.filter((row) => row.state === 'inconclusive').length, decay.length),
}

/**
 * Replace every marked region in a document.
 * @param text - document contents.
 * @param path - path, for error messages and the region language.
 * @returns the rewritten document.
 */
function rewrite(text, path) {
  const lang = path === 'README.zh.md' ? 'zh' : 'en'
  const seen = new Set()
  const pattern = /<!-- census:begin ([a-z0-9-]+) -->\n?([\s\S]*?)<!-- census:end \1 -->/g
  const out = text.replace(pattern, (match, name) => {
    const build = REGIONS[name]
    if (!build) {
      throw new Error(`${path}: region "${name}" has no generator; add it to REGIONS or fix the marker`)
    }
    seen.add(name)
    const body = build(lang)
    // Single-value regions stay on one line so surrounding prose reads normally.
    return body.includes('\n')
      ? `<!-- census:begin ${name} -->\n${body}\n<!-- census:end ${name} -->`
      : `<!-- census:begin ${name} -->${body}<!-- census:end ${name} -->`
  })
  // An unterminated marker would silently keep its old contents. Counting per
  // name catches a dangling `begin` even when the same region is matched
  // elsewhere in the file, which a "was this name seen?" check does not.
  const begins = new Map()
  const ends = new Map()
  for (const marker of out.matchAll(/<!-- census:(begin|end) ([a-z0-9-]+) -->/g)) {
    const bucket = marker[1] === 'begin' ? begins : ends
    bucket.set(marker[2], (bucket.get(marker[2]) ?? 0) + 1)
  }
  for (const name of new Set([...begins.keys(), ...ends.keys()])) {
    const opened = begins.get(name) ?? 0
    const closed = ends.get(name) ?? 0
    if (opened !== closed) {
      throw new Error(
        `${path}: marker "${name}" has ${opened} begin and ${closed} end marker(s); they must pair up`,
      )
    }
    if (!seen.has(name)) {
      throw new Error(`${path}: marker "${name}" is not part of a matched begin/end pair`)
    }
  }
  return out
}

const checkOnly = process.argv.includes('--check')
let stale = 0

for (const file of ['README.md', 'README.zh.md']) {
  const path = `${ROOT}${file}`
  const before = readFileSync(path, 'utf8')
  const after = rewrite(before, file)
  if (before === after) {
    process.stdout.write(`${file}: current\n`)
    continue
  }
  stale += 1
  if (checkOnly) {
    process.stdout.write(`${file}: STALE\n`)
    continue
  }
  writeFileSync(path, after)
  process.stdout.write(`${file}: rewritten\n`)
}

if (checkOnly && stale > 0) {
  process.stderr.write(
    `\n${stale} file(s) disagree with data/. Run \`node scripts/render-readme.mjs\` and commit the result.\n`,
  )
  process.exit(1)
}
