#!/usr/bin/env node
/**
 * Regenerate the data-derived figures in README.md and README.zh.md.
 *
 * Every number in those files used to be typed by hand while `data/*.jsonl` was
 * regenerated by a scheduled workflow, so the two could only diverge. Measured
 * on 2026-08-18: the READMEs claimed 6929 enumerated, 1698 probed and 1167
 * catalogued while the data held 7111, 2398 and 1660. The repository's own claim
 * is that its figures are reproducible, so a stale figure is not a cosmetic
 * problem.
 *
 * Prose stays hand-written. Only regions between the markers below are replaced:
 *
 *   <!-- census:begin NAME -->
 *   ...generated...
 *   <!-- census:end NAME -->
 *
 * A marker naming an unknown region, or a region with no marker, is an error
 * rather than a silent no-op: a typo would otherwise leave a figure frozen while
 * the rest updated, which is the failure this script exists to remove.
 *
 *   node scripts/render-readme.mjs            # rewrite in place
 *   node scripts/render-readme.mjs --check    # exit 1 if anything is stale
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const ROOT = new URL('..', import.meta.url).pathname

/** Read a JSONL file into records, or null when it does not exist yet. */
function load(name) {
  if (!existsSync(`${ROOT}data/${name}.jsonl`)) return null
  return readFileSync(`${ROOT}data/${name}.jsonl`, 'utf8')
    .split('\n')
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line))
}

/** Count occurrences of a field value. */
function tally(rows, key) {
  const counts = new Map()
  for (const row of rows) counts.set(row[key], (counts.get(row[key]) ?? 0) + 1)
  return counts
}

/** Format a share of a total to one decimal place. */
function share(count, total) {
  return total === 0 ? '0%' : `${((count / total) * 100).toFixed(1)}%`
}

const raw = load('repos-raw')
const contract = load('contract-v3')
const surface = load('surface-v3')
const install = load('installability-v3')
const decay = load('decay')
const catalog = load('catalog')
const reviews = load('reviews')
const npmManifest = load('npm-manifest') ?? []

const verdicts = tally(contract, 'verdict')
const catalogued = verdicts.get('CONTRACT_OK') ?? 0
const reviewed = reviews.filter((row) => row.reviewed)

/** Star band membership, in the order published. */
const BANDS = [
  ['0', (stars) => stars === 0],
  ['1-2', (stars) => stars >= 1 && stars <= 2],
  ['3-9', (stars) => stars >= 3 && stars <= 9],
  ['10-49', (stars) => stars >= 10 && stars <= 49],
  ['50+', (stars) => stars >= 50],
]

const starsByRepo = new Map(raw.map((row) => [row.full_name, row.stars ?? 0]))

/** Compliance share per star band, plus the overall row. */
function complianceRows(labels) {
  const rows = []
  let okAll = 0
  let nAll = 0
  for (const [label, inBand] of BANDS) {
    let ok = 0
    let n = 0
    for (const row of contract) {
      const stars = starsByRepo.get(row.repo)
      if (stars === undefined || !inBand(stars)) continue
      n += 1
      if (row.verdict === 'CONTRACT_OK') ok += 1
    }
    okAll += ok
    nAll += n
    const value = share(ok, n)
    rows.push(`| ${label} | ${label === '50+' ? `**${value}**` : value} |`)
  }
  rows.push(`| ${labels.all} | ${share(okAll, nAll)} |`)
  return rows.join('\n')
}

/** Verdict table, ordered by count then name so ties are stable. */
function verdictRows() {
  return [...verdicts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([verdict, count]) => `| \`${verdict}\` | ${count} | ${share(count, contract.length)} |`)
    .join('\n')
}

/** Surface-attribution table with a fixed row order and localised bases. */
function surfaceRows(basis) {
  const counts = tally(surface, 'confidence')
  return ['high', 'declared', 'medium', 'low', 'none']
    .map((level) => {
      const count = counts.get(level) ?? 0
      return `| \`${level}\` | ${basis[level]} | ${count} | ${share(count, surface.length)} |`
    })
    .join('\n')
}

/** Installability table. */
function installRows(meanings) {
  const counts = tally(install, 'installable')
  return ['published', 'git-only', 'unpublishable-scope']
    .map((state) => `| \`${state}\` | ${meanings[state]} | ${counts.get(state) ?? 0} |`)
    .join('\n')
}

/** Decay table, with the never-observed states pinned at zero. */
function decayRows() {
  const counts = tally(decay, 'state')
  return ['live', 'archived', 'gone', 'unbundled', 'dormant', 'inconclusive']
    .map((state) => `| \`${state}\` | ${counts.get(state) ?? 0} |`)
    .join('\n')
}

/**
 * Entries flagged as actually decayed, with the list capped.
 *
 * `inconclusive` is deliberately excluded: it means the probe could not reach a
 * conclusion, not that the entry decayed, and listing it as a flag would report
 * a quota shortfall as a property of someone's repository. Its count is published
 * separately through the `n-inconclusive` region.
 *
 * The list is capped because it is prose, not data — `data/decay.jsonl` is the
 * complete record. An uncapped table reached 450 lines once the catalogue grew.
 *
 * @param labels - localised header, column names, empty message and overflow note.
 * @returns markdown.
 */
function decayFlagged(labels) {
  const DECAYED = ['gone', 'archived', 'dormant', 'unbundled']
  const flagged = decay
    .filter((row) => DECAYED.includes(row.state))
    .sort((a, b) => a.state.localeCompare(b.state) || a.repo.localeCompare(b.repo))
  if (flagged.length === 0) return labels.empty
  const shown = flagged.slice(0, 12)
  const lines = [
    labels.header(flagged.length),
    '',
    `| ${labels.entry} | ${labels.state} |`,
    '| --- | --- |',
    ...shown.map((row) => `| \`${row.repo}\` | ${row.state}${row.detail ? ` — ${row.detail}` : ''} |`),
  ]
  if (flagged.length > shown.length) {
    lines.push('', labels.more(flagged.length - shown.length))
  }
  return lines.join('\n')
}

/** Score distribution over mean scores, rounded to the nearest whole score. */
function scoreRows(meanings) {
  const counts = new Map()
  for (const row of reviewed) {
    const bucket = Math.round(row.score)
    counts.set(bucket, (counts.get(bucket) ?? 0) + 1)
  }
  return [5, 4, 3, 2, 1]
    .map((score) => {
      const count = counts.get(score) ?? 0
      return `| ${score} | ${meanings[score]} | ${count} | ${share(count, reviewed.length)} |`
    })
    .join('\n')
}

const multiSampled = reviewed.filter((row) => (row.runs ?? 1) > 1)
const disagreeing = multiSampled.filter((row) => Math.max(...row.scores) !== Math.min(...row.scores))

/** Meanings for the published-manifest states, kept beside the region. */
const NPM_MEANINGS = {
  'bundle-ok': 'the published manifest declares `dsh.bundle`',
  'bundle-missing': '**the published manifest declares no `dsh.bundle`** — DSH refuses it as a profile bundle',
  'package-missing': 'the declared name no longer resolves on the registry',
  unreadable: 'the registry could not be read; not a statement about the package',
}

/** Chinese meanings for the same states. */
const NPM_MEANINGS_ZH = {
  'bundle-ok': '已发布的清单声明了 `dsh.bundle`',
  'bundle-missing': '**已发布的清单没有 `dsh.bundle`**——DSH 会拒绝把它作为 profile bundle 加载',
  'package-missing': '声明的包名已无法在 registry 上解析',
  unreadable: 'registry 读取失败；这不是对该包的判断',
}

/** Regions for both files. Keys must match the markers in the documents. */
const REGIONS = {
  'compliance-en': () => complianceRows({ all: 'all' }),
  'compliance-zh': () => complianceRows({ all: '全部' }),
  'verdicts': verdictRows,
  'surface-en': () => surfaceRows({
    high: 'depends on `@deepseek-ai/dsh-client-*` (client) or `@deepseek-ai/dsh-host-*` and host-only packages (host)',
    declared: "the plugin's own `dsh.client` or `dsh.host` block declares the surface",
    medium: 'depends on `@deepseek-ai/*`, but no dependency distinguishes client from host — surface `indeterminate`',
    low: 'no `@deepseek-ai/*` dependency; surface guessed from a name or description keyword',
    none: 'no dependency evidence and no keyword match — **not attributed at all**',
  }),
  'surface-zh': () => surfaceRows({
    high: '依赖 `@deepseek-ai/dsh-client-*`（client 侧）或 `@deepseek-ai/dsh-host-*` 及 host 专用包（host 侧）',
    declared: '插件自己的 `dsh.client` 或 `dsh.host` 块声明了该 surface',
    medium: '有 `@deepseek-ai/*` 依赖，但没有一个依赖能区分 client 与 host，surface 记为 `indeterminate`',
    low: '没有 `@deepseek-ai/*` 依赖，surface 由名称或描述中的关键词猜测',
    none: '既无依赖证据也无关键词命中——**根本没有归因**',
  }),
  'install-en': () => installRows({
    published: 'the declared name resolves on the npm registry',
    'git-only': 'absent from npm; installable from a Git specifier',
    'unpublishable-scope': 'names itself under `@deepseek-ai/` from a repository outside that organisation',
  }),
  'install-zh': () => installRows({
    published: '声明的包名可在 npm registry 解析',
    'git-only': '不在 npm 上；只能用 Git specifier 安装',
    'unpublishable-scope': '仓库不属于该组织，却用 `@deepseek-ai/` 命名自己',
  }),
  'decay': decayRows,
  'decay-flagged-en': () => decayFlagged({
    header: (n) => `The ${n} entries flagged as decayed (\`inconclusive\` is not decay and is excluded):`,
    entry: 'Entry',
    state: 'State',
    empty: 'No entry is currently flagged as decayed.',
    more: (n) => `...and ${n} more in \`data/decay.jsonl\`.`,
  }),
  'decay-flagged-zh': () => decayFlagged({
    header: (n) => `被判定为失效的 ${n} 个条目（\`inconclusive\` 不是失效，已排除）：`,
    entry: '条目',
    state: '状态',
    empty: '当前没有条目被判定为失效。',
    more: (n) => `……另有 ${n} 个见 \`data/decay.jsonl\`。`,
  }),
  'scores-en': () => scoreRows({
    5: 'substantial, documented, tested',
    4: 'solid and usable',
    3: 'ordinary, thin, undocumented',
    2: 'barely a plugin',
    1: 'empty or broken',
  }),
  'scores-zh': () => scoreRows({
    5: '扎实、有文档、有测试',
    4: '可用，文档足以让人采用',
    3: '一般，实现单薄、缺文档',
    2: '勉强算插件',
    1: '空的或坏的',
  }),
  // Inline figures, kept as single-value regions so prose can wrap around them.
  'n-enumerated': () => String(raw.length),
  'n-probed': () => String(contract.length),
  'n-catalogued': () => String(catalogued),
  'n-reviewed': () => String(reviewed.length),
  'n-multi': () => String(multiSampled.length),
  'n-disagree': () => String(disagreeing.length),
  'n-identical': () => String(multiSampled.length - disagreeing.length),
  'mean-spread': () => (multiSampled.length === 0
    ? 'n/a'
    : (
      multiSampled.reduce((sum, row) => sum + (Math.max(...row.scores) - Math.min(...row.scores)), 0)
      / multiSampled.length
    ).toFixed(2)),
  'max-spread': () => (multiSampled.length === 0
    ? 'n/a'
    : String(Math.max(...multiSampled.map((row) => Math.max(...row.scores) - Math.min(...row.scores))))),
  'n-declared': () => String(contract.filter((row) => (row.tier ?? 0) >= 1).length),
  'n-tier23-fail': () => String(
    contract.filter((row) => ['PATCH_FILE_MISSING', 'PATCH_FILE_EMPTY_OR_INVALID'].includes(row.verdict)).length,
  ),
  'n-vendored': () => String(verdicts.get('VENDORED_HARNESS') ?? 0),
  'n-catalog-rows': () => String(catalog.length),
  'max-age-days': () => {
    const ages = decay.map((row) => row.ageDays).filter((value) => typeof value === 'number')
    return ages.length === 0 ? 'unknown' : String(Math.max(...ages))
  },
  'n-dep-evidence': () => {
    const counts = tally(surface, 'confidence')
    return String((counts.get('high') ?? 0) + (counts.get('medium') ?? 0))
  },
  'n-declared': () => String(tally(surface, 'confidence').get('declared') ?? 0),
  'npm-manifest': () => {
    const counts = tally(npmManifest, 'state')
    const total = npmManifest.length
    return ['bundle-ok', 'bundle-missing', 'package-missing', 'unreadable']
      .map((state) => {
        const count = counts.get(state) ?? 0
        return `| \`${state}\` | ${NPM_MEANINGS[state]} | ${count} | ${share(count, total)} |`
      })
      .join('\n')
  },
  'npm-manifest-zh': () => {
    const counts = tally(npmManifest, 'state')
    const total = npmManifest.length
    return ['bundle-ok', 'bundle-missing', 'package-missing', 'unreadable']
      .map((state) => {
        const count = counts.get(state) ?? 0
        return `| \`${state}\` | ${NPM_MEANINGS_ZH[state]} | ${count} | ${share(count, total)} |`
      })
      .join('\n')
  },
  'n-npm-checked': () => String(npmManifest.length),
  'n-npm-broken': () => {
    const counts = tally(npmManifest, 'state')
    return String((counts.get('bundle-missing') ?? 0) + (counts.get('package-missing') ?? 0))
  },
  'pct-npm-broken': () => {
    const counts = tally(npmManifest, 'state')
    const bad = (counts.get('bundle-missing') ?? 0) + (counts.get('package-missing') ?? 0)
    return share(bad, npmManifest.length)
  },
  'n-inconclusive': () => String(decay.filter((row) => row.state === 'inconclusive').length),
  'pct-inconclusive': () => share(decay.filter((row) => row.state === 'inconclusive').length, decay.length),
  'review-mean': () => (reviewed.length === 0
    ? 'n/a'
    : (reviewed.reduce((sum, row) => sum + row.score, 0) / reviewed.length).toFixed(2)),
}

/**
 * Replace every marked region in a document.
 * @param text - document contents.
 * @param path - path, for error messages.
 * @returns the rewritten document.
 */
function rewrite(text, path) {
  const seen = new Set()
  const pattern = /<!-- census:begin ([a-z0-9-]+) -->\n?([\s\S]*?)<!-- census:end \1 -->/g
  const out = text.replace(pattern, (match, name) => {
    const build = REGIONS[name]
    if (!build) {
      throw new Error(`${path}: region "${name}" has no generator; add it to REGIONS or fix the marker`)
    }
    seen.add(name)
    const body = build()
    // Single-value regions stay on one line so surrounding prose reads normally.
    return body.includes('\n')
      ? `<!-- census:begin ${name} -->\n${body}\n<!-- census:end ${name} -->`
      : `<!-- census:begin ${name} -->${body}<!-- census:end ${name} -->`
  })
  // An unterminated marker would silently keep its old contents. Counting per
  // name catches a dangling `begin` even when the same region is matched
  // elsewhere in the file, which a "was this name seen?" check does not.
  const begins = new Map()
  const ends = new Map()
  for (const marker of out.matchAll(/<!-- census:(begin|end) ([a-z0-9-]+) -->/g)) {
    const bucket = marker[1] === 'begin' ? begins : ends
    bucket.set(marker[2], (bucket.get(marker[2]) ?? 0) + 1)
  }
  for (const name of new Set([...begins.keys(), ...ends.keys()])) {
    const opened = begins.get(name) ?? 0
    const closed = ends.get(name) ?? 0
    if (opened !== closed) {
      throw new Error(
        `${path}: marker "${name}" has ${opened} begin and ${closed} end marker(s); they must pair up`,
      )
    }
    if (!seen.has(name)) {
      throw new Error(`${path}: marker "${name}" is not part of a matched begin/end pair`)
    }
  }
  return out
}

const checkOnly = process.argv.includes('--check')
let stale = 0

for (const file of ['README.md', 'README.zh.md']) {
  const path = `${ROOT}${file}`
  const before = readFileSync(path, 'utf8')
  const after = rewrite(before, file)
  if (before === after) {
    process.stdout.write(`${file}: current\n`)
    continue
  }
  stale += 1
  if (checkOnly) {
    process.stdout.write(`${file}: STALE\n`)
    continue
  }
  writeFileSync(path, after)
  process.stdout.write(`${file}: rewritten\n`)
}

if (checkOnly && stale > 0) {
  process.stderr.write(
    `\n${stale} file(s) disagree with data/. Run \`node scripts/render-readme.mjs\` and commit the result.\n`,
  )
  process.exit(1)
}
