#!/usr/bin/env node
/**
 * Hold the conformance auditor to hand-verified expectations.
 *
 * The auditor's first implementation produced false positives on every
 * repository it was tried against — four for four, including a `no-manifest`
 * verdict for a repository whose manifest exists. Criteria count is worthless
 * without precision, so no criterion may enter the published catalogue until
 * it passes here.
 *
 * Expectations in `fixtures/labelled.json` were established by reading each
 * repository and are recorded with their evidence. They are deliberately NOT
 * derived from auditor output: a fixture set generated by the tool under test
 * cannot detect that tool's mistakes.
 *
 * Usage: test-audit.mjs <checkout-root>
 * `<checkout-root>/<owner>_<name>` must hold each fixture checkout, fetched
 * with scripts/fetch-checkout.sh so a truncated tree cannot be mistaken for a
 * repository defect.
 */

import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { audit } from './audit-repo.mjs'

const root = process.argv[2]
if (root === undefined) {
  process.stderr.write('usage: test-audit.mjs <checkout-root>\n')
  process.exit(2)
}

const spec = JSON.parse(readFileSync(new URL('../fixtures/labelled.json', import.meta.url), 'utf8'))
let failed = 0
let checked = 0
let skipped = 0

for (const fixture of spec.fixtures) {
  const dir = join(root, fixture.repo.replace('/', '_'))
  // A missing checkout fails rather than skips. Treating it as a skip let this
  // suite report success while testing fewer fixtures than it claims: a shell
  // loop dropped the last fixture name, the assertion count fell from 19 to 16,
  // and the run still exited 0. Absent evidence must not read as passing.
  if (!existsSync(dir)) {
    process.stdout.write(`  FAIL  ${fixture.repo}: no checkout at ${dir}\n`)
    process.stdout.write('        fetch it with scripts/fetch-checkout.sh before running this suite\n')
    failed += 1
    skipped += 1
    continue
  }

  const verdict = await audit(dir, fixture.repo)
  const reported = new Set(verdict.issues.map((issue) => issue.code))

  for (const code of fixture.mustReport ?? []) {
    checked += 1
    if (reported.has(code)) {
      process.stdout.write(`  PASS  ${fixture.repo}: reports ${code}\n`)
    } else {
      process.stdout.write(`  FAIL  ${fixture.repo}: must report ${code} but did not\n`)
      process.stdout.write(`        why it must: ${fixture.evidence?.[code] ?? '(no evidence recorded)'}\n`)
      failed += 1
    }
  }

  for (const code of fixture.mustNotReport ?? []) {
    checked += 1
    if (!reported.has(code)) {
      process.stdout.write(`  PASS  ${fixture.repo}: does not report ${code}\n`)
    } else {
      const detail = verdict.issues.find((issue) => issue.code === code)?.detail ?? ''
      process.stdout.write(`  FAIL  ${fixture.repo}: falsely reports ${code}\n`)
      process.stdout.write(`        auditor said: ${detail}\n`)
      process.stdout.write(`        ground truth: ${fixture.evidence?.[code] ?? '(no evidence recorded)'}\n`)
      failed += 1
    }
  }

  // Any error-severity finding outside the expected set is an unlabelled
  // regression: it may be genuine, but it must be investigated and labelled
  // before the catalogue publishes it as a defect in someone's repository.
  const expected = new Set([...(fixture.mustReport ?? []), ...(fixture.mustNotReport ?? [])])
  for (const issue of verdict.issues) {
    if (issue.severity !== 'error' || expected.has(issue.code)) continue
    process.stdout.write(`  FAIL  ${fixture.repo}: unlabelled error ${issue.code}\n`)
    process.stdout.write(`        ${issue.detail}\n`)
    process.stdout.write('        verify by hand, then add it to mustReport or mustNotReport with evidence\n')
    failed += 1
  }
}

// Report code paths the fixtures provably do NOT cover. A suite that stays
// green when a behaviour is removed does not test that behaviour, and leaving
// the gap unstated would let it be mistaken for verified.
const gaps = spec.fixtures.filter((fixture) => fixture.$unverifiedPath !== undefined)
if (gaps.length > 0) {
  process.stdout.write('\nknown coverage gaps (verified absent, not assumed):\n')
  for (const fixture of gaps) {
    process.stdout.write(`  GAP   ${fixture.repo}: ${fixture.$unverifiedPath}\n`)
  }
}

process.stdout.write(failed === 0
  ? `\nall ${checked} audit expectations held${skipped > 0 ? ` (${skipped} fixture(s) skipped)` : ''}`
    + `${gaps.length > 0 ? `, with ${gaps.length} documented coverage gap(s)` : ''}\n`
  : `\n${failed} of ${checked} audit expectations failed\n`)
process.exit(failed === 0 ? 0 : 1)
